### ISSUE TITLE
Use of uninitialized value in concatenation

### ISSUE THREAD

**Issue by hagenbauer** [derhansen/logwatch-modsec2#6]
[ip: 94.228.34.206  ] [id:  ] [msg: ]  - 3 time(s)
   [ip: 94.228.34.210  ] [id:  ] [msg: ]  - 7 time(s)
   [ip: 94.228.34.248  ] [id:  ] [msg: ]  - 6 time(s)
   [ip: 94.23.195.135  ] [id: 960009 ] [msg: Request Missing a User Agent Header]  - 1 time(s)
   [ip: 94.23.202.191  ] [id: 96000Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.
 Use of uninitialized value in concatenation (.) or string at /etc/logwatch/scripts/services/mod_security2 line 193, <STDIN> line 5445008.

**Comment by derhansen** [comment]
Could you provide me your audit logfile (mailto: derhansen@gmail.com), so I can check what goes wrong?

**Comment by derhansen** [comment]
Issue has been solved in version 1.0.1
