### ISSUE TITLE
Script floods logwatch's output.

### ISSUE THREAD

**Issue by ghost** [derhansen/logwatch-modsec2#7]
Good morning, 

if have discovered a possible issue with my setup (Ubuntu 12.04. Server, Apache2-mpm-itk):

Instead of logging the modsecurity output in the logfiles, logwatch floods my email reports with the following message:

Use of uninitialized value in pattern match (m//) at /etc/logwatch/scripts/services/mod_security2 line 164, <STDIN> 

followed by an ascending number, e.g:

"Use of uninitialized value in pattern match (m//) at /etc/logwatch/scripts/services/mod_security2 line 164, <STDIN> line 189...ascends up to 1210501."

I am relatively new to Ubuntu, Modsec, Apache etc, so i lack the ability to fix it for myself. Maybe someone else has an idea or this is just a bug? 

Sincerely, Bobuscho

**Comment by derhansen** [comment]
Could you provide me your audit logfile (derhansen@gmail.com), so I can check what goes wrong?

**Comment by derhansen** [comment]
Closed due to missing feedback.
